version: "3.9"
networks:
  default:
    name: tls-network
    internal: true
services:
  botan-server: 
    image: tls-botan
  openssl-server-wrong-cn: 
    image: tls-openssl
    command: [ "/openssl-server", "-k", "/etc/ssl/cert-data/wrong-cn.com.key", "-c" , "/etc/ssl/cert-data/wrong-cn.com-chain.crt"]
  openssl-malicious-alpn: 
    image: tls-openssl
    command: [ "/openssl-server", "-m"]
  botan-client: 
    image: tls-botan
    command: [ "/client.sh", "/client", "botan-server", "openssl-server-wrong-cn", "openssl-malicious-alpn" ,"1"]
    depends_on: 
      - botan-server
      - openssl-server-wrong-cn
      - openssl-malicious-alpn