version: "3.9"
networks:
  default:
    name: tls-network
    internal: true
services:
  httpd: 
    image: tls-apache
  scanner:
    image: tlsscanner
    depends_on:
      - httpd
    command: [ "-connect", "httpd:4433", "-server_name", "tls-server.com", "-scanDetail", "QUICK"]
