version: "3.9"
networks:
  default:
    name: tls-network
    internal: true
services:
  filezillaserver: 
    image: tls-filezillaserver
  scanner:
    image: tlsscanner
    depends_on:
    - filezillaserver
    command: [ "-connect", "filezillaserver:21", "-server_name", "tls-server.com", "-starttls", "ftp", "-scanDetail", "QUICK"]