version: "3.9"
networks:
  default:
    name: tls-network
    internal: true
services:
  tls-sendmail: 
    image: tls-sendmail
    hostname: tls-server.com
    container_name: tls-server.com
  scanner:
    image: tlsscanner
    depends_on:
     - tls-sendmail
    command: [ "-connect", "tls-server.com:25", "-server_name", "tls-server.com",  "-starttls", "SMTP", "-scanDetail", "QUICK"]
    restart: always