version: "3.9"
networks:
  default:
    name: tls-network
    internal: true
services:
  vsftpd: 
    image: tls-vsftpd
  scanner:
    image: tlsscanner
    depends_on:
    - vsftpd
    command: [ "-connect", "vsftpd:21", "-server_name", "tls-server.com", "-starttls", "ftp", "-scanDetail", "QUICK"]